CREATE TABLE IF NOT EXISTS clubs (
  id INTEGER PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  country VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS players (
  ID INTEGER PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  club_id INTEGER NOT NULL,
  nationality VARCHAR(100) NOT NULL,
  position VARCHAR(20) NOT NULL,

  overall INTEGER NOT NULL CHECK (overall BETWEEN 0 AND 99),
  pace INTEGER NOT NULL CHECK (pace BETWEEN 0 AND 99),
  shooting INTEGER NOT NULL CHECK (shooting BETWEEN 0 AND 99),
  passing INTEGER NOT NULL CHECK (passing BETWEEN 0 AND 99),
  dribbling INTEGER NOT NULL CHECK (dribbling BETWEEN 0 AND 99),
  physical INTEGER NOT NULL CHECK (physical BETWEEN 0 AND 99),

  CONSTRAINT players_club_fk
    FOREIGN KEY (club_id)
    REFERENCES clubs(id)
    ON DELETE RESTRICT
);
